### PR TITLE
Moved the Steps for Building for Linux out of the wiki into the docs folder

### PR DESCRIPTION
**Pull request by haennes**

### CODE REVIEW

**Comment by EhWhoAmI** [comment]
I think the name of the file is not very conventional. You should either put it into the `README.md` file, or in `docs/BUILDING_UBUNTU.md`

**Comment by z-adams** [comment]
Agreed, or even just BUILDING.md or something, I don't see a point in separating the build instructions by platform. If they're so long that they need to be separated, we're doing something wrong :)

**Comment by EhWhoAmI** [comment]
If you move it to `BUILDING.md`, you should also move the MSVC build instructions there. They're in `README.md`

**Comment by Capital-Asterisk** [comment]
I actually already have a branch on this, where the wiki and msvc instructions are merged into `docs/building.md` with minor formatting changes. The docs directory name is the same at least. Perhaps merging this into a section specific to debian/ubuntu?

https://github.com/Capital-Asterisk/osp-magnum/tree/inrepo-docs

**Comment by haennes** [comment]
> I actually already have a branch on this, where the wiki and msvc instructions are merged into `docs/building.md` with minor formatting changes. The docs directory name is the same at least. Perhaps merging this into a section specific to debian/ubuntu?
> 
> https://github.com/Capital-Asterisk/osp-magnum/tree/inrepo-docs

I will merge mine and your instructions into one if that is Ok for you.

**Comment by jonesmz** [comment]
> > I actually already have a branch on this, where the wiki and msvc instructions are merged into `docs/building.md` with minor formatting changes. The docs directory name is the same at least. Perhaps merging this into a section specific to debian/ubuntu?
> > https://github.com/Capital-Asterisk/osp-magnum/tree/inrepo-docs
> 
> I will merge mine and your instructions into one if that is Ok for you.

You can do that via a git rebase.

You'll want to add @Capital-Asterisk 's repository on github as an upstream repository. Then rebase your branch onto caps, so that you preserve the authorship.

**Comment by jonesmz** [comment]
@haennes did you have any luck with git rebase?

**Comment by haennes** [comment]
> @haennes did you have any luck with git rebase?

sorry, haven't tried that yet. I won't have time for this today sadly. I will try again tomorrow

**Comment by jonesmz** [comment]
Because this is only a documentation change, I'm merging this.

@haennes Thanks!

**Pull request merged**
