### PR TITLE
Add new Documentation: architecture.md and guidelines.md

### PR DESCRIPTION
**Pull request by Capital-Asterisk**
docs. Docs. DOCS!!!

I might add things to architecture, otherwise this is mostly ready to merge.

### CODE REVIEW

**Comment by Ben-Bingham** [comment]
I was just reading through guidlines.md, and couldn't figure this out so I figured I would put this here:

What should be the casing of a variable after an underscore prefix?
ie:
g_GlobalVariable
g_globalVariable

I honestly don't know which one is preferred so figured I would put it here, regardless, it would be helpful to place an additional example that clarifies which style is preferred on line 148ish of guidlines.md

**Comment by jonesmz** [comment]
There's also this style guide document that I wrote.
Not sure how far diverged you've gotten from it: https://docs.google.com/document/d/1dJW-E6SN41XQuvidHRhp41O_1mJmP90bar1egZ31c10/edit?usp=sharing

**Comment by jonesmz** [comment]
and in general all the docs here probably need overhauled: https://drive.google.com/drive/folders/1zSpXs7tiBI3XmGx9dwlHiqxjRaB997lC?usp=drive_link

**Review by jonesmz — APPROVED** [review]
Ah, i see you linked the google doc directly.

**Comment by jonesmz** [comment]
> I was just reading through guidlines.md, and couldn't figure this out so I figured I would put this here:
> 
> What should be the casing of a variable after an underscore prefix? ie: g_GlobalVariable g_globalVariable
> 
> I honestly don't know which one is preferred so figured I would put it here, regardless, it would be helpful to place an additional example that clarifies which style is preferred on line 148ish of guidlines.md

camelCase generally has the first letter lowercased.

`g_` is the prefix, `globalVariable` would be the "word", so lowercase the first letter of the word.

**Comment by Capital-Asterisk** [comment]
> > I was just reading through guidlines.md, and couldn't figure this out so I figured I would put this here:
> > What should be the casing of a variable after an underscore prefix? ie: g_GlobalVariable g_globalVariable
> > I honestly don't know which one is preferred so figured I would put it here, regardless, it would be helpful to place an additional example that clarifies which style is preferred on line 148ish of guidlines.md
> 
> camelCase generally has the first letter lowercased.
> 
> `g_` is the prefix, `globalVariable` would be the "word", so lowercase the first letter of the word.

I mean, the example is missing. time to push directly to master

**Pull request merged**
