### PR TITLE
zooming set to +/- 0.3 times current zoom

### PR DESCRIPTION
**Pull request by flindt**
Suggested alternative to issue #83

### CODE REVIEW

**Comment by z-adams** [comment]
I think the point of that issue was actually that the scroll is too slow at large zoom values, so this way would only fix it in the other direction. Maybe @EhWhoAmI can clarify what he meant.

**Comment by flindt** [comment]
Yes, I'd agree it was way too slow.

The point of my suggestion is that zoom change is proportional with current zoom level - increasing the steps at large zoom values.  
This way one click on the scroll wheel feels the same whether you are close or far away from the ship.

**Comment by EhWhoAmI** [comment]
Yeah, I meant it to be proportion to what the zoom level is. My suggestion was based off my guess of the zoom in code before I took a look, so it may be inaccurate

**Comment by EhWhoAmI** [comment]
I tested it out, and if you zoom out far enough, it will keep zooming in and out by itself, making it a bit epileptic. 

But otherwise, the zoom is much more bearable.

**Comment by Capital-Asterisk** [comment]
This is a nice change.

> I tested it out, and if you zoom out far enough, it will keep zooming in and out by itself, making it a bit epileptic.
> 
> But otherwise, the zoom is much more bearable.

When you zoom out too far, the vehicle unloads. Since the vehicle is still selected by the camera controller, it will move towards it until it is back in the active area.

On line 181, change this
```cpp
// round to nearest (floatingOriginThreshold)
Vector3s tra = Vector3s(xform.translation() / floatingOriginThreshold)
             * floatingOriginThreshold;
```

To this, so that the floating origin is centered on the vehicle instead of the camera.
```cpp
// round to nearest (floatingOriginThreshold)
Vector3s tra = Vector3s((xform.translation() - m_orbitPos) / floatingOriginThreshold)
             * floatingOriginThreshold;
```

**Comment by flindt** [comment]
How did this break the windows build?

**Comment by Capital-Asterisk** [comment]
> How did this break the windows build?

This happens a few times, it's github changing things in the build environment. The build is actually successful, it's the artifact release that failed because it seems the files are now built in a different directory.

**Comment by EhWhoAmI** [comment]
Yeah, don't worry

**Review by jonesmz — APPROVED** [review]

**Comment by EhWhoAmI** [comment]
Is this good to merge? If it is I'll just merge it.

**Review by EhWhoAmI — APPROVED** [review]

**Pull request merged**
